### PR TITLE
Add Twig and Plates extensions

### PR DESCRIPTION
**Pull request by dborsatto**
This PR adds support for integrating this library with templating engines Twig and Plates.

### CODE REVIEW

**Comment by dlitvakb** [comment]
I'm not entirely sure that we should provide this integrations within the package, as it means adding external dependencies that may pull in A LOT of framework dependencies that are strictly not necessary for most people that are going to be using this library.

I would go for a separate package for the helpers, or to include it in the current extensions we already have.

**Comment by dborsatto** [comment]
Actually, they don't add any dependency to users of this library. The dependencies are only included when working on this library, but if you include it in your project, they won't be added (they are in the `require-dev` section of the config file, not in the `require`).

**Comment by dlitvakb** [comment]
I'm still a bit sceptic about this, as users may have dependency issues if they choose the incorrect bridge, but if you think it's going to be alright, then I'm ok with your decision.

**Comment by dlitvakb** [comment]
That's exactly what I meant though, having the dependency error is not good. Because the unaware user, instead of changing the bridge to the correct one, they may install dependencies to shut the thing up.

**Comment by dborsatto** [comment]
No, because it will never cause an error if you don't try to use the bridge. This library works completely fine without it, it's built not to force any dependency.

The only error would happen if you intentionally use the TwigExtension and you don't have Twig installed, but if you do so, it's not this library's fault to be honest. It can't cause any sort of conflict because it doesn't define a dependency, and it's also how all packages implement optional dependencies: it's just there, and it's so explicitly opt-in that you must know what you're doing if you use it...

**Pull request merged**
